# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
    - source
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
  - openssl aes-256-cbc -K $encrypted_2c430460807a_key -iv $encrypted_2c430460807a_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "gaoupon"
  - git config --global user.email "gaoupon@163.com"
  # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
  # - curl -o- -L https://yarnpkg.com/install.sh | bash
  # - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli
install:
  # 不用yarn的话这里改成 npm i 即可
  - npm i
script:
  - hexo clean
  - hexo generate
after_success:
  - scp -o stricthostkeychecking=no -r public/* travis@47.99.132.117:/home/travis/blog
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  # 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
  - git push --quiet --force https://$REPO_TOKEN@github.com/gaoupon/gaoupon.github.io.git
    master
